[package]
name = "brotli-sys"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
build = "build.rs"
links = "brotli"
license = "MIT/Apache-2.0"
repository = "https://github.com/alexcrichton/brotli-rs"
homepage = "https://github.com/alexcrichton/brotli-rs"
documentation = "http://alexcrichton.com/brotli-rs"
description = """
Raw bindings to libbrotli
"""

[dependencies]
libc = "0.2"

[build-dependencies]
gcc = "0.3"
